version: '2'

services:
    cloudera:
        image: cloudera/quickstart:latest
        container_name: cloudera
        privileged: true
        hostname: quickstart.cloudera
        stdin_open: true
        tty: true
        command: /usr/bin/docker-quickstart
        ports:
            - "7180:7180"
            - "8888:8888"
