version: '2'

services:
    cloudera:
        image: cloudera/quickstart:latest
        container_name: cloudera
        privileged: true
        hostname: quickstart.cloudera
        stdin_open: true
        tty: true
        command: /usr/bin/docker-quickstart
        ports:
            - "80:80"
            - "7180:7180"
            - "8088:8088"
            - "8888:8888"
            - "10002:10002"
            - "19888:19888"
            - "60010:60010"
